version: '3'
services:
  backend:
    image: purplehyacinth087/courses_api
    ports:
      - "8000:8000"
  frontend:
    image: purplehyacinth087/courses-ui
    ports:
      - "3000:3000"
    depends_on:
      - backend
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: courses
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: cvbghj456
    ports:
      - "5432:5432"
